from setuptools import setup, find_packages

setup(
    name="fastsqs",
    version="1.1.0",
    description="FastAPI-like, lightweight SQS message processing for Python (routing + middleware + dependency injection)",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Gabriel LaFayette",
    author_email="gabriel.lafayette@proton.me",
    url="https://github.com/imgabrieldev/fastsqs",
    packages=find_packages(),
    package_data={"fastsqs": ["py.typed"]},
    install_requires=["pydantic>=2.0.0", "fast-depends>=3.0.0,<4.0.0"],
    python_requires=">=3.10",
    license="MIT",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Distributed Computing",
    ],
    keywords="sqs aws lambda serverless async fastapi pydantic message-processing",
    include_package_data=True,
)
